import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [

    {
      type: "category",
      label: "onboard",
      link: {
        type: "generated-index",
        title: "onboard",
        slug: "/category/datamarketplace-api/onboard",
      },
      items: [
        {
          type: "doc",
          id: "datamarketplace-api/onboard-login",
          label: "Login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/onboard-register",
          label: "Register",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/onboard-refresh-token",
          label: "Refresh token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/onboard-list-sectors",
          label: "List sectors",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/onboard-get-code-of-conduct",
          label: "Download code of conduct",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "config",
      link: {
        type: "generated-index",
        title: "config",
        slug: "/category/datamarketplace-api/config",
      },
      items: [
        {
          type: "doc",
          id: "datamarketplace-api/config-read-admin",
          label: "Read admin",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-update-admin",
          label: "Update admin",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-reset-password",
          label: "Reset password",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-admin-reset",
          label: "Reset connections and verifications",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-read-data-source",
          label: "Read data source",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-create-data-source",
          label: "Create data source",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-update-data-source",
          label: "Update data source",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-read-data-source-cover-image",
          label: "Get data source cover image",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-update-data-source-cover-image",
          label: "Update data source cover image",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-read-data-source-logo-image",
          label: "Get data source logo image",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-update-data-source-logo-image",
          label: "Update data source logo image",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-read-verification",
          label: "Read verification",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-create-verification",
          label: "Create verification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-update-open-api-url",
          label: "Update Open API URL",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-list-verification-templates",
          label: "List verification templates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-create-connection",
          label: "Create connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-list-connections",
          label: "List connections",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-delete-connection",
          label: "Delete connection",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-list-dd-as",
          label: "List data disclosure agreements",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-read-dda",
          label: "Read data disclosure agreement",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-delete-dda",
          label: "Delete data disclosure agreement",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-update-dda-status",
          label: "Update DDA status",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-update-dda-tags",
          label: "Update DDA tags",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-list-dda-history",
          label: "List DDA history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/config-delete-dda-history",
          label: "Delete DDA history entry",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "organisation",
      link: {
        type: "generated-index",
        title: "organisation",
        slug: "/category/datamarketplace-api/organisation",
      },
      items: [
        {
          type: "doc",
          id: "datamarketplace-api/organisation-read",
          label: "Read organisation",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-update",
          label: "Update organisation",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-update-code-of-conduct",
          label: "Update code of conduct acceptance",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-read-cover-image",
          label: "Get organisation cover image",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-update-cover-image",
          label: "Update organisation cover image",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-read-logo-image",
          label: "Get organisation logo image",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-update-logo-image",
          label: "Update organisation logo image",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-read-identity",
          label: "Read organisation identity",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-create-identity",
          label: "Create organisation identity verification",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-delete-identity",
          label: "Delete organisation identity",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-read-software-statement",
          label: "Read software statement",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-create-software-statement",
          label: "Create software statement",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-delete-software-statement",
          label: "Delete software statement",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-create-o-auth-2-client",
          label: "Create OAuth2 client",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-read-o-auth-2-client",
          label: "Read OAuth2 client",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-update-o-auth-2-client",
          label: "Update OAuth2 client",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-delete-o-auth-2-client",
          label: "Delete OAuth2 client",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-list-o-auth-2-clients",
          label: "List OAuth2 clients",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-create-external-o-auth-2-client",
          label: "Create external OAuth2 client",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-read-external-o-auth-2-client",
          label: "Read external OAuth2 client",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-update-external-o-auth-2-client",
          label: "Update external OAuth2 client",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-delete-external-o-auth-2-client",
          label: "Delete external OAuth2 client",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-list-external-o-auth-2-clients",
          label: "List external OAuth2 clients",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-read-b-2-b-connection",
          label: "Read B2B connection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-list-b-2-b-connections",
          label: "List B2B connections",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-sign-dda",
          label: "Sign DDA with business wallet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-get-dda-signing-status",
          label: "Get DDA signing status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-read-signed-agreement",
          label: "Read signed agreement record",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-delete-signed-agreement",
          label: "Delete signed agreement record",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "datamarketplace-api/organisation-list-signed-agreements",
          label: "List signed agreement records",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "service",
      link: {
        type: "generated-index",
        title: "service",
        slug: "/category/datamarketplace-api/service",
      },
      items: [
        {
          type: "doc",
          id: "datamarketplace-api/service-list-data-sources",
          label: "List data sources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/service-get-data-source-cover-image",
          label: "Get data source cover image (2)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/service-get-data-source-logo-image",
          label: "Get data source logo image (2)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/service-list-organisations",
          label: "List organisations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/service-get-organisation-cover-image",
          label: "Get organisation cover image (2)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/service-get-organisation-logo-image",
          label: "Get organisation logo image (2)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/service-search",
          label: "Search organisations and DDAs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/service-data-space-configuration",
          label: "Data space configuration discovery",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/service-o-auth-server-metadata",
          label: "OAuth authorization server metadata",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "datamarketplace-api/service-get-token",
          label: "OAuth2 token endpoint",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/service-notification",
          label: "Receive notifications",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "webhook",
      link: {
        type: "generated-index",
        title: "webhook",
        slug: "/category/datamarketplace-api/webhook",
      },
      items: [
        {
          type: "doc",
          id: "datamarketplace-api/webhook-connections",
          label: "Connection webhook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/webhook-present-proof",
          label: "Present proof webhook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/webhook-published-dda",
          label: "Published DDA webhook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/webhook-ows-present-proof",
          label: "OWS present proof webhook",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "datamarketplace-api/webhook-ows-issue-credential",
          label: "OWS issue credential webhook",
          className: "api-method post",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
